version: "3.9" # pode ser 3.0, mas 3.9 é o mais usado hoje
services:
  ms-consulta:
    build:
      context: ./ms-consulta
      dockerfile: Dockerfile
    container_name: ms_consulta
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
  ms-notificacao:
    build:
      context: ./ms-notificacao
      dockerfile: Dockerfile
    container_name: ms_notificacao
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
  ms-historico:
    build:
      context: ./ms-historico
      dockerfile: Dockerfile
    container_name: ms_historico
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mydb", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
  email:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" # acesso externo (host)
      - "29092:29092" # acesso interno (entre containers)
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      # Identificação do broker
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Configs básicas
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: >
      sh -c "
        sleep 10 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic notificacao_consulta --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      "
volumes:
  postgres_data:
